version: '3.8'

volumes:
  pg-data:
    external: false

networks:
  internal-network:
    driver: bridge

services:
  postgres-spring:
    image: postgres:14-alpine
    container_name: postgres
    restart: always
    env_file:
      - .env.local
    volumes:
      - pg-data:/var/lib/postgresql/data:rw
    ports:
      - "5433:5432"
    networks:
      - internal-network
